# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Faster Matrix Multiplication
#'
#' Faster matrix multiplication using C++.
#'
#' @param A,B Matrices.
#' @export
eigenMapMatMult <- function(A, B) {
    .Call(`_icWGCNA_eigenMapMatMult`, A, B)
}

